<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => '',
    'Cart' => '',
    'Categories' => '',
    'Category' => '',
    'Category Translate' => '',
    'Companies' => '',
    'Company' => '',
    'Company Balance' => '',
    'Company Transaction' => '',
    'Company Transactions' => '',
    'CompanyTransaction' => '',
    'Contract' => '',
    'Create Product' => '',
    'Favorite' => '',
    'Order' => '',
    'Order List' => '',
    'Order Lists' => '',
    'Order Request' => '',
    'Order Requests' => '',
    'OrderList' => '',
    'OrderRequest' => '',
    'Orders' => '',
    'Page' => '',
    'Page Translate' => '',
    'Pages' => '',
    'Product' => '',
    'Product Image' => '',
    'Product Images' => '',
    'Product Property' => '',
    'Product Translate' => '',
    'ProductImage' => '',
    'Products' => '',
    'Properties' => '',
    'Property' => '',
    'Property Translate' => '',
    'Property Value' => '',
    'Property Value Translate' => '',
    'Property Values' => '',
    'PropertyValue' => '',
    'Region' => '',
    'Region Translate' => '',
    'Regions' => '',
    'Updata Product' => '',
    'Update Product' => '',
    'User' => '',
    'User Profile' => '',
    'User Profiles' => '',
    'UserProfile' => '',
];
