<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A link to reset password will be sent to your email.' => '',
    'Are you sure you want to delete this category?' => '',
    'Are you sure you want to delete this company?' => '',
    'Are you sure you want to delete this order-request?' => '',
    'Are you sure you want to delete this order?' => '',
    'Are you sure you want to delete this page?' => '',
    'Are you sure you want to delete this product-image?' => '',
    'Are you sure you want to delete this product?' => '',
    'Are you sure you want to delete this property?' => '',
    'Are you sure you want to delete this region?' => '',
    'Are you sure you want to delete this user?' => '',
    'Cancel' => '',
    'Create' => '',
    'Create User' => '',
    'Created At' => '',
    'Delete' => '',
    'Economy' => '',
    'Email' => '',
    'ID' => '',
    'Image' => '',
    'Login' => '',
    'New password ( if you want to change it )' => '',
    'Password' => '',
    'Please choose your new password:' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Please fill out your email.' => '',
    'Published' => '',
    'Request password reset' => '',
    'Reset password' => '',
    'Role' => '',
    'Save' => '',
    'Send' => '',
    'Sign In' => '',
    'Sport' => '',
    'Status' => '',
    'The above error occurred while the Web server was processing your request.' => '',
    'Update' => '',
    'Update User' => '',
    'Updated At' => '',
    'Username' => '',
    'Users' => '',
    'Вы уверены, что хотите удалить этот элемент?' => '',
];
